#! /bin/zsh
# sim start

if [ $# -gt 0 ]; then
    runs=$1
else
    runs=1
fi
echo "run ${runs} times"


for i in $(seq 1 ${runs}); do
    (${lilibot}) &
    sleep 20
    echo "turn direction"
    rosparam set /VRN_hip_L1 0.055
    rosparam set /VRN_hip_L2 0.055

    rosparam set /VRN_hip_L3 0.035
    rosparam set /VRN_hip_L4 0.035
    sleep 20
    rosnode kill /control_node
    sleep 3
done

echo "Experiments Done!"


