#! /bin/zsh
# sim start

if [ $# -gt 0 ]; then
    runs=$1
else
    runs=1
fi


echo "run ${runs} times"
for i in $(seq 1 ${runs}); do
    (${lilibot}) &
    sleep 40
    rosnode kill /control_node
    sleep 3
done
echo "Experiments Done!"
