#! /bin/zsh
# sim start

if [ $# -gt 0 ]; then
   runs=$1
else
   runs=1
fi
echo "run ${runs} times"
for i in $(seq 1 ${runs}); do
rostopic pub --once /sim_control/startSimulation std_msgs/Bool "data: true"

sleep 110

rostopic pub --once /sim_control/stopSimulation std_msgs/Bool "data: true"
done
echo "Experiments Done!"

