#! /bin/zsh
# sim start

# running times
if [ $# -gt 0 ]; then
    runs=$1
else
    runs=1
fi

echo "run ${runs} times"
# files
# The content of this file will be crated by stbot_node
data_log_file_path=$HOME/workspace/experiment_data/datapath.log
data_log_file=$HOME/workspace/experiment_data/ExperimentDataLog.log
echo "" > $data_log_file #create a experiment data log file or empty the log
rostopic pub --once /sim_control/floorInclination std_msgs/Float32 "data: 0.0"


for offset_value in -0.3 -0.2 -0.1  0.0 0.1 0.2 0.3
#for offset_value in -0.3 0.3
do
    for i in $(seq 1 $runs); do
        rostopic pub --once /sim_control/startSimulation std_msgs/Bool "data: true"
        eval "rosparam set /MNB2_L1 ${offset_value}"
        eval "rosparam set /MNB3_L1 ${offset_value}"
        eval "rosparam set /MNB2_L2 ${offset_value}"
        eval "rosparam set /MNB3_L2 ${offset_value}"
        eval "rosparam set /MNB2_L3 ${offset_value}"
        eval "rosparam set /MNB3_L3 ${offset_value}"
        eval "rosparam set /MNB2_L4 ${offset_value}"
        eval "rosparam set /MNB3_L4 ${offset_value}"
        sleep 30 #22 #32 #55 
        rostopic pub --once /sim_control/stopSimulation std_msgs/Bool "data: true"
        data_path_temp=$(cat $data_log_file_path)
        echo "$data_path_temp\t$offset_value">> $data_log_file
    done
    sleep 4
done

echo "Experiments Done!"

